OCP Dataset Refactor
IntelLabs/matsciml pull request #103
Opened 2024-01-19 21:33 UTC by melo-gonzo

This PR refactors the ocp datasets (S2EF, IS2RE) to be `PointCloudDatasets`. This is in preperation of moving to dgl 2.0. The PR includes updated tests and examples, as well as an updated IS2RE devset.

2024-01-20 00:22 UTC, laserkelvin commented
Related to #98

2024-01-22 22:41 UTC, laserkelvin requested changes

2024-01-22 22:41 UTC, laserkelvin commented on examples/model_demos/faenet_pyg.py
>              GraphToGraphTransform("pyg"),
If we're converting from point cloud to graph, then we should just be able to go straight to PyG right? This `GraphToGraph` is not needed?

2024-01-22 22:41 UTC, laserkelvin commented on examples/model_demos/gala.py
> +            PointCloudToGraphTransform(
Wait, why do you need to transform to graphs for GALA?

2024-01-22 22:41 UTC, laserkelvin commented on matsciml/datasets/transforms/representations/tests/test_graph_transform.py
>      def test_dgl_ocp_special():
I don't think this test is needed anymore; I wrote it because we were converting OCP graphs to point clouds via that transform, which we don't need now.

2024-01-22 22:41 UTC, laserkelvin commented on matsciml/datasets/utils.py
> +    eye = torch.eye(max_types, dtype=int)
Interesting, where/what kind of error did you get?

I don't have a problem with this, just curious when and where it came out as an issue

2024-01-22 22:57 UTC, melo-gonzo commented on examples/model_demos/gala.py
> +            PointCloudToGraphTransform(
Ha - so looking a bit closer at this, this file has never actually been a Gala demo, it has always had SchNet. I can either make it actually be a gala example, or we can remove the file - Gala is already demonstrated in `./examples/datasets/materials_project/single_task_gala.py`.

2024-01-22 23:00 UTC, laserkelvin commented on examples/model_demos/gala.py
> +            PointCloudToGraphTransform(
Okay, get rid of it LOL

2024-01-22 23:22 UTC, melo-gonzo commented on matsciml/datasets/utils.py
> +    eye = torch.eye(max_types, dtype=int)
not actually seeing any error from this anymore, so i reverted this. cant exactly remember which dataset/pipeline was throwing the error in the first place.

2024-01-22 23:22 UTC, melo-gonzo commented on matsciml/datasets/transforms/representations/tests/test_graph_transform.py
>      def test_dgl_ocp_special():
purged this test

2024-01-22 23:23 UTC, melo-gonzo commented on examples/model_demos/faenet_pyg.py
>              GraphToGraphTransform("pyg"),
good eye - updated this to go straight to pyg.

2024-01-23 00:26 UTC, laserkelvin requested changes
Just made one last comment, then good to go

2024-01-23 00:26 UTC, laserkelvin commented on matsciml/datasets/utils.py
> +    return feat_tensor.to(torch.float)
Pedantic, but code style wise I would prefer `feat_tensor.float()`

2024-01-23 21:52 UTC, melo-gonzo commented on matsciml/datasets/utils.py
> +    return feat_tensor.to(torch.float)
done!

2024-01-23 22:01 UTC, laserkelvin approved these changes
LGTM

2024-01-23 22:06 UTC, laserkelvin commented
Note for future @melo-gonzo for tracking: will need to reprocess IS2RE dataset on Zenodo

2024-01-23 22:06 UTC, merged