Adding support for ColabFit Datasets
IntelLabs/matsciml pull request #109
Opened 2024-01-29 16:20 UTC by EFuem

This is my initial implementation of a ColabFitDataset. I have a few questions regarding how you'd like things done:

1. Is how I am setting ``target_keys`` ok? We currently have 7 properties supported between all datasets. I didn't see an issue with including all 7 as targets even though datasets will only contain some of these.
2. I didn't see a task in which stresses could be used as a target. Should I remove support for this or is it a plan to support this in the future?

On my end, I still need to streamline the infrastructure for LMDB generation and download for everything we have. I also need to think more deeply about more robust testing/error handling. For example, I believe there are some datasets in which the original creators did not include the same number of potential target properties for all samples, e.g., not including stress for some samples. Being able to warn users about this and other issues would be useful.

2024-01-30 22:10 UTC, melo-gonzo requested changes
Thanks for the PR, this looks great! I noted a few small updates. My larger question is if you plan to include an interface to ColabFit in this PR or another? Not sure it makes too much of a difference, just asking for the sake of logistics.

2024-01-30 22:20 UTC, melo-gonzo requested changes

2024-01-30 22:20 UTC, melo-gonzo commented on matsciml/datasets/colabfit/dataset.py
> +    def collate_fn(batch: list[DataDict]) -> BatchDict:
Add `BatchDict` to imports.

2024-01-30 22:20 UTC, melo-gonzo commented on matsciml/datasets/colabfit/README.md
> +If you utlize the ColabFit Exchange to access data, please cite the original creators of the dataset you use and refer to [this link](https://colabfit.org/about/) for how to cite ColabFit itself.
Small typo, utilize.

2024-01-30 22:20 UTC, melo-gonzo commented on matsciml/datasets/colabfit/dataset.py
> +        for key in POSSIBLE_KEYS:
I think the handling of `target_keys` looks fine. If someone is curating their own ColabFit dataset they should presumably know what keys will be available to them, and if they ask for something not included they'll be met with an error anyway.

2024-02-01 22:41 UTC, EFuem commented
I have made the small changes.

> Thanks for the PR, this looks great! I noted a few small updates. My larger question is if you plan to include an interface to ColabFit in this PR or another? Not sure it makes too much of a difference, just asking for the sake of logistics.

At the moment there are two ways (or will be) to obtain dataset files-through the website or through a CLI package that I have developed. Obviously the website will always be an option, but whether are not to add the CLI or its components here or just treat it as an external tool (and link to it as is done in the README) is still an open question. There is a third option-support taking in a dataset identifier as an argument to `ColabFitDataset` and then downloading the associated files if not present. However, users would need know what datasets are on ColabFit in the first place (and what the dataset identifiers are) so it may make sense to just default to the first two options.  I am open to suggestions though.

2024-02-02 16:21 UTC, laserkelvin approved these changes

2024-02-02 16:21 UTC, laserkelvin commented on matsciml/datasets/colabfit/dataset.py
> +    def index_to_key(self, index: int) -> tuple[int]:
So this only really needs to be overwritten if you ever intend to just have a single `lmdb` file, but normally this shouldn't be needed (I don't think?). Would you be able to check if this works without overwriting this method?

2024-02-02 16:21 UTC, laserkelvin commented on matsciml/datasets/colabfit/dataset.py
> +        for key in POSSIBLE_KEYS:
Am I correct in thinking that `POSSIBLE_KEYS` is based on what *can* be possible from ColabFit, but the point is that the user might not serialize every property?

2024-02-02 16:24 UTC, laserkelvin commented
Stand alone the PR looks good to me. Just chiming in to the discussion above:

> At the moment there are two ways (or will be) to obtain dataset files-through the website or through a CLI package that I have developed. Obviously the website will always be an option, but whether are not to add the CLI or its components here or just treat it as an external tool (and link to it as is done in the README) is still an open question. There is a third option-support taking in a dataset identifier as an argument to ColabFitDataset and then downloading the associated files if not present. However, users would need know what datasets are on ColabFit in the first place (and what the dataset identifiers are) so it may make sense to just default to the first two options. I am open to suggestions though.

I think we discussed offline last time that IMO it would be good to be able to track the origin of the data within LMDB files: I'm okay to not include the CLI you've written in `matsciml`, but preferably, the CLI will serialize something that includes what datasets, keys, etc. were requested and when, and when the LMDB conversion happens, we dump that information into the `metadata` `dict` as well.

2024-02-02 16:47 UTC, EFuem commented on matsciml/datasets/colabfit/dataset.py
> +    def index_to_key(self, index: int) -> tuple[int]:
The devset test works with this removed.

2024-02-02 16:49 UTC, laserkelvin commented on matsciml/datasets/colabfit/dataset.py
> +    def index_to_key(self, index: int) -> tuple[int]:
I would suggest removing it then, just so that the class will work with multiple LMDB files

2024-02-02 16:53 UTC, laserkelvin commented on matsciml/datasets/colabfit/dataset.py
> +        for key in POSSIBLE_KEYS:
So I've been debating internally about how to treat this kind of "informational" thing and open to discussions that don't really have to happen inside this PR. Boiling down to _why_ does the user need to know if they're missing keys - as in genuinely, under what circumstances would a user need to know, and what would they be able to do with that information?

This broadly pertains to keys that may or may not be available, like Materials Project. I think the warning message (or even a `KeyError`) should be shown *if* the user specifies it in the `task_keys` specification of a training task, but is missing, since then the user is actually intending to train with it. Otherwise, I don't know if it's needed to have this kind of check within a `Dataset` class?

2024-02-02 16:54 UTC, laserkelvin commented on matsciml/datasets/colabfit/dataset.py
> +    def index_to_key(self, index: int) -> tuple[int]:
Done in fbd22d8

2024-02-02 17:09 UTC, melo-gonzo approved these changes

2024-02-05 16:37 UTC, merged