Model contribution guide
IntelLabs/matsciml pull request #121
Opened 2024-02-13 20:52 UTC by laserkelvin

This PR adds notes on how to test functionality for new model contributions, and provides a working example for the PyG flavor of EGNN.

Some valuable feedback from review would be whether the instructions are clear, and whether using `pytest` makes the bar to entry a little too high.

2024-02-13 22:37 UTC, melo-gonzo requested changes
Looks great overall! Made a few comments of small things to update. I 'followed along' and implemented `CarmeloNet` (SOTA in no benchmarks currently), and this all seemed to flow nicely.

2024-02-13 22:37 UTC, melo-gonzo commented on matsciml/models/README.md
> +        embeddings = egnn_architecture(batch)
`egnn_architecture` should be `model_fixture` I believe.

2024-02-13 22:37 UTC, melo-gonzo commented on matsciml/models/README.md
> +At a high level, model implementations in Open MatSciML are expected to emit a system-level embedding; i.e. $B$
All the B's and D's could be consolidated here for clarity: "... emit DxB embeddings where dimension D is some hyper parameter of your model and B is the minibatch size."

2024-02-13 22:37 UTC, melo-gonzo commented on matsciml/models/README.md
> +        return graph_feats
Shouldn't our AmazingModel be returning an `Embeddings` object?

2024-02-13 22:37 UTC, melo-gonzo commented on matsciml/models/README.md
> +as they do not need to rely on framework abstractions to perform message passing. Tt is still best
Small typo (Tt -> It).

2024-02-13 22:37 UTC, melo-gonzo commented on matsciml/models/README.md
> +from matsciml.datases.transforms import PeriodicPropertiesTransform, PointCloudToGraphTransform
Small typo :`.datases` -> `.datasets`

2024-02-13 22:37 UTC, melo-gonzo commented on matsciml/models/README.md
> +from matsciml.models import NewModel
For completeness, we can add:
```python
import torch

from matsciml.lightning.data_utils import MatSciMLDataModule
```

2024-02-13 23:19 UTC, laserkelvin commented on matsciml/models/README.md
> +        return graph_feats
Very good catch, I literally just grabbed it from out of date docs!

2024-02-13 23:36 UTC, laserkelvin commented on matsciml/models/README.md
> +as they do not need to rely on framework abstractions to perform message passing. Tt is still best
Fixed in 9cf499

2024-02-13 23:53 UTC, laserkelvin commented on matsciml/models/README.md
> +from matsciml.datases.transforms import PeriodicPropertiesTransform, PointCloudToGraphTransform
Fixed in df3a1e9

2024-02-13 23:53 UTC, laserkelvin commented on matsciml/models/README.md
> +from matsciml.models import NewModel
Fixed in 45c404c

2024-02-13 23:53 UTC, laserkelvin commented on matsciml/models/README.md
> +        embeddings = egnn_architecture(batch)
Fixed in 6a5c2ca

2024-02-13 23:53 UTC, laserkelvin commented on matsciml/models/README.md
> +At a high level, model implementations in Open MatSciML are expected to emit a system-level embedding; i.e. $B$
Fixed in c63e762

2024-02-13 23:53 UTC, laserkelvin commented on matsciml/models/README.md
> +        return graph_feats
Fixed in c63e762

2024-02-14 00:05 UTC, melo-gonzo commented
Thanks for the updates. My only other comments are that I think the pytest bits should remain, and be required. Ultimately, it's not too difficult to implement at least some minimal tests, especially with examples already in the repo. Let's leave this up for a day or so to see if any more feedback comes in.

2024-02-20 19:35 UTC, laserkelvin commented
We've left this up for a bit now - what do you think @melo-gonzo ?

2024-02-20 19:38 UTC, melo-gonzo commented
I'm good to have this merged in. Was waiting to see if there was any other feedback. I thinnk the silence means everyone is happy. Approving!

2024-02-20 19:38 UTC, melo-gonzo approved these changes

2024-02-20 19:43 UTC, merged