Upgrade matgl to 1.0.0
IntelLabs/matsciml pull request #126
Opened 2024-02-15 19:54 UTC by melo-gonzo

This PR upgrades the matgl package to 1.0.0. This includes many refactors on their end. In matsciml, the `M3G` datasets are removed, and replaced by a transform, `MGLDataTransform`, which adds the required keys to train m3gnet. Also added in a test for m3gnet specifically.

2024-02-15 20:51 UTC, laserkelvin requested changes

2024-02-15 20:51 UTC, laserkelvin commented on matsciml/models/dgl/tests/test_m3gnet.py
Just to be certain, what passes and fails with this test?

2024-02-15 20:51 UTC, laserkelvin commented on matsciml/datasets/transforms/matgl_datasets.py
> +        graph.edata["pbc_offset"] = graph.edata["offsets"]
Can you add an assertion here where if this key is missing, it throws a message to remind people to include the transform?

2024-02-15 20:51 UTC, laserkelvin commented on matsciml/datasets/transforms/matgl_datasets.py
> +        graph.edata["pbc_offshift"] = torch.matmul(
Are these keys the ones that are specifically needed by `matgl`?

2024-02-15 20:51 UTC, laserkelvin commented on matsciml/datasets/transforms/matgl_datasets.py
> +        data["graph"] = graph
I don't think you need this since we are writing to the graph directly

2024-02-15 21:01 UTC, melo-gonzo commented on matsciml/models/dgl/tests/test_m3gnet.py
The OQMD and SyntheticPointGroupDataset datasets will cause this test to fail, due to missing `lattice_params` keys and `atomic_numbers`.
```python
FAILED matsciml/models/dgl/tests/test_m3gnet.py::test_model_forward_nograd[OQMDDataset] - KeyError: 'Data sample is missing lattice parameters. Ensure `lattice_features` or `lattice_params` is available in the data.'
FAILED matsciml/models/dgl/tests/test_m3gnet.py::test_model_forward_nograd[SyntheticPointGroupDataset] - AssertionError: atomic_numbers missing from data sample!
```

2024-02-15 21:02 UTC, melo-gonzo commented on matsciml/datasets/transforms/matgl_datasets.py
> +        graph.edata["pbc_offshift"] = torch.matmul(
Yes, they are used throughout the codebase, and will be required for TensorNet as well.

2024-02-15 21:03 UTC, melo-gonzo commented on matsciml/datasets/transforms/matgl_datasets.py
> +        graph.edata["pbc_offset"] = graph.edata["offsets"]
Added assertion in [6ce49cc](https://github.com/IntelLabs/matsciml/pull/126/commits/6ce49cc607ef7be105aeaf8fd6e511ab35a3982b)

2024-02-15 21:08 UTC, laserkelvin commented on matsciml/datasets/transforms/matgl_datasets.py
> +            graph.edata["pbc_offset"], data["cell"][0]
I'm not 100% sure about the mapping for `pbc_offset` and `pbc_offshift` compared to the results of our transforms: to me, it seems like `pbc_offshift` resembles `offsets`, and it depends on how `pbc_offset` is used, but could be `unit_offsets`?

2024-02-15 21:09 UTC, laserkelvin commented on matsciml/models/dgl/tests/test_m3gnet.py
Sweet, good to know!

I won't "resolve" this conversation just so that it doesn't get hidden

2024-02-15 21:27 UTC, melo-gonzo commented on matsciml/datasets/transforms/matgl_datasets.py
> +            graph.edata["pbc_offset"], data["cell"][0]
After looking a bit closer I think you're right. Their [pbc_offset](https://github.com/materialsvirtuallab/matgl/blob/12ded8c302f9ac9fc23d388bdbd652fb1589cf50/src/matgl/graph/converters.py#L56) is just the images, and the pbc_offshift is our [offsets](https://github.com/melo-gonzo/matsciml/blob/c6dddfe4d99a7abb88fe025c337b735e4cac95c7/matsciml/datasets/utils.py#L719).

Let me know if that sounds right to you.

2024-02-16 00:08 UTC, laserkelvin commented on matsciml/datasets/transforms/matgl_datasets.py
> +            graph.edata["pbc_offset"], data["cell"][0]
I think it seems right. I tried to make my naming convention not as confusing...

Anyhow, make the changes and let's keep this convo open. I'll approve as well so you can merge after you push the change.

2024-02-16 00:08 UTC, laserkelvin approved these changes

2024-02-16 00:16 UTC, merged