Add alexandria dataset to matsciml toolkit https://github.com/IntelLabs/matsciml/discussions/107
IntelLabs/matsciml pull request #132
Opened 2024-02-19 10:25 UTC by JonathanSchmidt1

This pull request adds the AlexandriaRequest class to download the Alexandria database to an lmdb dataset and a AlexandriaDataset class to use it for ML within the matsciml toolkit.
The AlexandriaDataset class mostly follows  the Materials project example.
I also added most of the same tests.
At the moment there are not test for  the AlexandriaRequest class.

2024-02-20 18:52 UTC, laserkelvin requested changes
Thanks @JonathanSchmidt1 for the great PR!!

For the most part things look good and functional to me; I did leave a few style remarks, and wanted to see if you could add a PyG test as well. If you don't normally use that pipeline, don't worry about it and we can add it later.

2024-02-20 18:52 UTC, laserkelvin commented on matsciml/datasets/alexandria/README.md
> +with a further publication.
Do you mind adding a list of target keys here and give a quick summary of each property - e.g. what units they use, and anything else that might be relevant?

2024-02-20 18:52 UTC, laserkelvin commented on matsciml/datasets/alexandria/dataset.py
> +            110,
Is there a reason you went with 110 here?

2024-02-20 18:52 UTC, laserkelvin commented on matsciml/datasets/alexandria/dataset.py
> +            _ = self.__getitem__(0)
This is more of a style comment than anything: normally `_` is set when you don't care about the variable but you just need to unpack it, but you do end up using it in the case below so I'd prefer it you named it like `sample` or something

2024-02-20 18:52 UTC, laserkelvin commented on matsciml/datasets/alexandria/dataset.py
> +        targets = targets | {
Does this statement work on our lowest version of Python @melo-gonzo?

It might work with `from __future__ import annotations` and that's definitely true for type annotations but I wasn't sure if it works as an operator. Can you try running a snippet like this in a container you use?

2024-02-20 18:52 UTC, laserkelvin commented on matsciml/datasets/alexandria/dataset.py
> +        targets = {
For the sake of readibility I might actually suggest calling the two `dict`s as `regression_targets` and `classification_targets`. You can still do 

```python
targets = regression_targets | classification_targets
```

But this way IMO the intention is more clear even if it's more verbose

2024-02-20 18:52 UTC, laserkelvin commented on matsciml/datasets/alexandria/dataset.py
> +class AlexandriaDataset(PointCloudDataset):
More a comment for discussion with @melo-gonzo but the fact that @JonathanSchmidt1 had to copy over a bunch of functions here means we could do better on the abstraction: what do you think?

2024-02-20 18:52 UTC, laserkelvin commented on matsciml/datasets/alexandria/tests/test_alexandria.py
> +    assert len(batch["atomic_numbers"]) == 10
Is this right? One atom per batch sample.

Just making sure!

2024-02-20 18:52 UTC, laserkelvin commented on matsciml/datasets/alexandria/tests/test_alexandria.py
> +def test_graph_transform():
Would it be a big ask for you to add a PyG transform test as well?

2024-02-20 18:52 UTC, melo-gonzo requested changes
Thanks for the PR! It looks pretty good overall, I've left a few initial comments. In addition to what was noted, can you add some details to the [DATASETS.md](https://github.com/melo-gonzo/matsciml/tree/main/matsciml/datasets#documenting-new-datasets:~:text=Documenting%20new%20datasets) as well? It's a bit redundant but for consistency it will be nice to have some details in there as well.

2024-02-20 18:52 UTC, melo-gonzo commented on examples/model_demos/mpnn_alexandria_dgl.py
Thanks for including an example! Since this is a new dataset, the example may be better placed in `examples/datasets/alexandria/single_task_devset.py`.

2024-02-20 18:52 UTC, melo-gonzo commented on matsciml/datasets/alexandria/README.md
Can you also add a basic script snippet to show how to download the full dataset? Similar to [Carolina Materials Database](https://github.com/melo-gonzo/matsciml/tree/main/matsciml/datasets/carolina_db#:~:text=To%20download%20the%20full%20dataset%2C%20the%20CMDRequest%20module%20from%20matsciml/datasets/carolina_db/carolina_api.py%20may%20be%20used%20as%20follows%3A) or [OQMD](https://github.com/melo-gonzo/matsciml/tree/main/matsciml/datasets/oqmd#:~:text=A%20simple%20python%20script%20may%20be%20used%20to%20query%2C%20save%20and%20process%20the%20data%20into%20an%20lmdb%20file%3A). Additionally, it would be idea to have the default full dataset download options included into the [`./scripts/download_datasets.py`](https://github.com/melo-gonzo/matsciml/blob/main/scripts/download_datasets.py) script as well.

2024-02-20 18:52 UTC, melo-gonzo commented on matsciml/datasets/alexandria/api.py
> +from matsciml.datasets.alexandria import AlexandriaDataset
There's some unused imports in here that can be removed.

2024-02-20 18:52 UTC, melo-gonzo commented on matsciml/datasets/alexandria/dataset.py
> +            110,
@laserkelvin do you know if having different `max_types` for the point_cloud_featurization` will cause problems in a multi-data scenario? I can test this, but it's not something we've done so far.

2024-02-20 18:53 UTC, laserkelvin commented
LOL the timing on our reviews

2024-02-20 19:08 UTC, laserkelvin commented on matsciml/datasets/alexandria/dataset.py
> +            110,
Yeah it would cause problems if it's used naively, but the caveat is if we're using point clouds, this featurization might actually be done by the model `_read_batch` step anyway in order to have it backprop through to the atomic numbers (which is why IIRC this is [done here](https://github.com/IntelLabs/matsciml/blob/7afb766a093bf1fb3c18d733707726472088070d/matsciml/models/base.py#L335).) 

If anything it might mean we don't need to do this step in the data loading, which we can refactor out later.

2024-02-21 15:45 UTC, JonathanSchmidt1 commented on examples/model_demos/mpnn_alexandria_dgl.py
thanks I added examples similar to the materials project and moved them

2024-02-21 15:53 UTC, JonathanSchmidt1 commented on matsciml/datasets/alexandria/dataset.py
> +            _ = self.__getitem__(0)
changed _ to sample

2024-02-21 18:30 UTC, JonathanSchmidt1 commented
Thank you for both of the reviews. I will go through them today and tomorrow.
I noticed one issue that the way periodic boundary conditions are dealt with was updated over the last weeks when my graphtransform test failed.
How is the output of a periodic graph supposed to look after the transformation with [PeriodicPropertiesTransform(20.), PointCloudToGraphTransform('pyg', cutoff_dist=20.0)] now?
i.e. Are the edges supposed to show the edges including boundary conditions already? Or is this calculated somewhere else later based on the shifts and offsets (if yes where?).

btw maybe it's an issue for the materials project dataset also but for my dataset the check for precomputed src and dst nodes lead to there only being self loops in the end 
```
g.edge_index
tensor([[0, 1, 2],
        [0, 1, 2]])

```
instead of
```
tensor([[1, 2, 2],
        [0, 0, 1]])
```
with the check commented out

2024-02-21 18:42 UTC, JonathanSchmidt1 commented
ok the first question solved itself. Now I am just wondering about the edge case if you do not use the PeriodicPropertiesTransform
but the materials project or Alexandria dataset you already have src/dst nodes set from the PointCloudDataset choose_dst_nodes method. However these do not seem to be the correct edges to me e.g. with a cutoff of 40 I would expect connections between the different atoms:
```
>>> dset.__getitem__(0)['graph'].edge_index
tensor([[0, 1, 2],
        [0, 1, 2]])
>>> dset.__getitem__(0)['graph'].pos
tensor([[ 0.0000,  0.0000,  0.0000],
        [22.0659,  4.5494,  2.7011],
        [ 6.3406,  1.3073,  0.7761]])

```
but maybe I am missunderstanding the edge indices

2024-02-21 19:07 UTC, JonathanSchmidt1 commented on matsciml/datasets/alexandria/dataset.py
> +class AlexandriaDataset(PointCloudDataset):
The parse_structure/parse_symmetry functions from the materials project class seems quite general. Maybe it makes sense to put them in some utils file instead and import them in the respective datasets.

2024-02-21 20:14 UTC, JonathanSchmidt1 commented on matsciml/datasets/alexandria/tests/test_alexandria.py
> +def test_graph_transform():
I added two pyg transform tests https://github.com/IntelLabs/matsciml/pull/132/commits/b1ce3af847843cfd7dca4b4f592ab6849ed0c247

2024-02-21 20:22 UTC, JonathanSchmidt1 commented on matsciml/datasets/alexandria/dataset.py
> +            110,
Fixed it to 100

2024-02-21 20:24 UTC, JonathanSchmidt1 commented on matsciml/datasets/alexandria/README.md
I added a download script example in the dataset examples and added options for the various datasets to the script.

2024-02-26 17:09 UTC, laserkelvin commented
> but in the materials project or Alexandria dataset you already have src/dst nodes set from the PointCloudDataset choose_dst_nodes method. However these do not seem to be the correct edges to me e.g. with a cutoff of 40 I would expect connections between the different atoms (this is related to the second point in the previous question):

To be clear (I don't know if this is a misunderstanding or not so forgive me) the function `choose_dst_nodes` is probably poorly named, because point clouds don't have edges. That function is used to construct featurizations for point clouds but are not related to *graph edge construction*, so the cut-off radii do not come into play at all. That's why I think `edge_index` don't make sense

If you want to understand the graph edge construction, there are basically two implemented paths now: the `cutoff_radius` value is applied either by an explicit dense matrix distance calculation (if there is no `cell` attribute in the data sample, i.e. assume it's basically like a molecular graph) or if there is `cell`, we rely on `pymatgen` to compute the connectivity.

2024-03-01 17:33 UTC, melo-gonzo commented on matsciml/datasets/alexandria/dataset.py
> +        targets = targets | {
Can confirm that this doesn't work in python <= 3.8. It would be good to switch up these statements for compatibility.

2024-03-01 17:34 UTC, melo-gonzo commented on matsciml/datasets/alexandria/dataset.py
> +class AlexandriaDataset(PointCloudDataset):
Agreed, a lot of this can be refactored into some sort of utils file - it would make all the datasets much cleaner. I can draft up an issue for this.

2024-03-01 17:37 UTC, laserkelvin commented on matsciml/datasets/alexandria/dataset.py
> +        targets = targets | {
In fairness, Python 3.8 is end of life this year so maybe we should just move to Python 3.9+ as supported versions. That would be a separate PR however.

For this specific PR my recommendation is to rewrite it without using the syntatic sugar.

2024-03-04 08:46 UTC, JonathanSchmidt1 commented on matsciml/datasets/alexandria/dataset.py
> +        targets = targets | {
changed it to
```
classification_targets = {
            key: self._standardize_values(data["targets"]["classification"][key])
            for key in data["targets"].get("classification", {}).keys()
        }
targets = targets.update(classification_targets)``

2024-03-04 08:52 UTC, JonathanSchmidt1 commented
@laserkelvin One question concerning the test that I did not completely understand is still open. The rest should be ready for rereview.

2024-03-06 00:28 UTC, laserkelvin commented
I'm out of office for the rest of the week and I'll review it once I get back.

2024-03-11 19:14 UTC, laserkelvin commented on matsciml/datasets/alexandria/api.py
> +        if self.devset:
Would it make sense to move this up so you don't run all of the requests for devsets? That way you don't use too much server load if you don't need to.

2024-03-11 19:18 UTC, laserkelvin commented on matsciml/datasets/alexandria/dataset.py
> +        structure: None | Structure = Structure.from_dict(data.get("structure", None))
If you are unpacking a `pymatgen.core.Structure`, could you also add the `Lattice` object to the data dict?

This should get reused by the `PeriodicPropertiesTransform` and make it consistent across datasets.

i.e.

```python
cell = torch.from_numpy(structure.lattice.matrix).float()
return_dict["cell"] = cell
```

2024-03-11 19:23 UTC, laserkelvin commented on matsciml/datasets/alexandria/tests/test_alexandria.py
> +    assert len(batch["atomic_numbers"]) == 10
Ahh sorry, in my head I thought the tensor was padded and concatenated. My mistake!

2024-03-12 09:31 UTC, JonathanSchmidt1 commented on matsciml/datasets/alexandria/api.py
> +        if self.devset:
I can move it up one step  so we run self.get_data_dict only for the 100 entries. Right now we only have the database split up into the 100k structure jsons so one has to download at least one of them (and it also will only  be one of them for the devset so that should not be an issue for the server).
```
     def devset(cls, lmdb_target_dir: str) -> AlexandriaRequest:
        return cls([0], lmdb_target_dir, dataset="3D", devset=True)
```

2024-03-12 10:29 UTC, JonathanSchmidt1 commented on matsciml/datasets/alexandria/__init__.py
> +alexandria_devset = Path(__file__).parents[0].joinpath("devset")
:+1:

2024-03-12 10:32 UTC, JonathanSchmidt1 commented on matsciml/datasets/alexandria/dataset.py
> +        structure: None | Structure = Structure.from_dict(data.get("structure", None))
:+1:   added the cell to the return dict

2024-03-12 10:35 UTC, JonathanSchmidt1 commented on examples/datasets/alexandria/single_task_devset.py
> +            PeriodicPropertiesTransform(20.0),
I reduced it to 10

2024-03-12 10:35 UTC, JonathanSchmidt1 commented on examples/datasets/alexandria/single_task_egnn.py
> +            PeriodicPropertiesTransform(20.0),
I reduced it to 10

2024-03-12 19:10 UTC, melo-gonzo reviewed
A few more minor updates from my end, and then will be good to approve!

2024-03-12 19:10 UTC, melo-gonzo commented on examples/datasets/alexandria/single_task_base.py
> +dm = MatSciMLDataModule(
Can you update the examples to use `MatSciMLDataModule.from_devset`? Using this means also taking out the `val_split` as well.

2024-03-12 19:10 UTC, melo-gonzo commented on examples/datasets/alexandria/single_task_egnn.py
> +dm = MatSciMLDataModule(
Update to use `.from_devset`

2024-03-12 19:10 UTC, melo-gonzo commented on examples/datasets/alexandria/single_task_gala.py
> +dm = MatSciMLDataModule(
Update to use `.from_devset`

2024-03-12 23:21 UTC, laserkelvin approved these changes
I just highlighted the unused import flagged by `pre-commit`, but other than that I'm giving my approval for merging.

2024-03-13 16:12 UTC, melo-gonzo approved these changes

2024-03-13 16:20 UTC, laserkelvin commented
I think we're good to go - I looked into the failing tests and nothing is relevant to this PR.

Thank you @JonathanSchmidt1 for all your hard work on this PR!

2024-03-13 16:20 UTC, merged