Adding FA Transform Back In
IntelLabs/matsciml pull request #134
Opened 2024-02-21 20:04 UTC by melo-gonzo

Frame averaging transform was removed in [this](https://github.com/IntelLabs/matsciml/commit/34d2677c3c51357f1a35f1574dd36e22758f7142) commit by ruff. There doesn't seem to be a great solution to prevent ruff from removing unused imports, and also for allowing * imports. I added `# noqa: F403` to get around this for now.

2024-02-26 15:58 UTC, laserkelvin requested changes

2024-02-26 15:58 UTC, laserkelvin commented on matsciml/datasets/transforms/frame_averaging.py
> +    raise Exception("torch_geometric is required for Frame Averaging transform.")
You want to probably use `ModuleNotFoundError` instead.

As a side note, it's more that it's just implemented for PyG right now and not DGL right? I would suggest "Frame averaging transform is only currently implemented for PyG."

2024-02-26 17:45 UTC, melo-gonzo commented on matsciml/datasets/transforms/frame_averaging.py
> +    raise Exception("torch_geometric is required for Frame Averaging transform.")
updated in [d212fdf](https://github.com/IntelLabs/matsciml/pull/134/commits/d212fdf7170fb63b81d02ffdfb93dcc302d6778d)

2024-03-01 16:32 UTC, laserkelvin approved these changes

2024-03-01 16:50 UTC, laserkelvin commented
Apparently 2 reviewers are needed for this review, so I added @smiret-intel

2024-03-01 18:49 UTC, smiret-intel approved these changes

2024-03-01 18:49 UTC, merged