Materials Project Devset Update
IntelLabs/matsciml pull request #195
Opened 2024-04-19 21:30 UTC by melo-gonzo

Updating the devset to have all the same target keys as the full dataset.

2024-04-22 21:47 UTC, melo-gonzo commented
Added the update to the failing test. I had to rewrite a bit of the logic due to the order of target keys in the list not being preserved.

2024-04-23 14:42 UTC, laserkelvin commented
It still seems to be failing - I can't tell if the test hasn't updated?

2024-05-08 16:22 UTC, melo-gonzo commented
@laserkelvin can you have another look at this?

2024-05-08 18:03 UTC, laserkelvin requested changes

2024-05-08 18:04 UTC, laserkelvin approved these changes

2024-05-08 18:09 UTC, melo-gonzo commented on matsciml/lightning/tests/test_multi_module.py
> +    # assert keys == expected
fixed here [36b6130](https://github.com/IntelLabs/matsciml/pull/195/commits/36b6130524f569042b8cacbb0ceacaa8c14cc75f)

2024-05-08 18:12 UTC, merged