Experiments Running and Management
IntelLabs/matsciml pull request #246
Opened 2024-06-27 16:50 UTC by melo-gonzo

This PR adds functionality to run and manage experiments in matsciml. Currently, the options for experimentation are to create a script for each experiment run and manually update parameters, or to use the pytorch lightning cli + yaml files. The first approach is time-consuming and clumsy, and the second approach does not handle multi task and multi data experiments in matsciml. This PR aims to bridge the gap between functional experimental pipelines without the headache of managing a ton of scripts. It takes inspiration from the lightning cli by managing the different aspects of an experiment with yaml files `{trainer, model, dataset, experiment}.yaml` and allows for cli updates by specifying a chain of parameters to traverse and update. Experimentation effectively comes down to managing these yaml files and greatly reduces the barrier to entry towards running complex experiments with multi task and multi data origins. See the README for more details.

2024-06-27 17:26 UTC, melo-gonzo commented
Note that I updated `matsciml/models/dgl/gaanet/tests/test_gala.py` and `matsciml/models/base.py` to match changes from #228.

2024-07-01 19:53 UTC, laserkelvin requested changes
I've put in some minor comments, but the two high level things that I'll bring up for discussion are:

1. Maybe we can _finally_ use the registry, so instead of maintaining individual maps in task, dataset, and models, just rely on `matsciml.common.registry` to do the mapping?
2. I'm not sure if I missed it, but it might be good to refactor your object creation functions (i.e. mapping `args` into something you pull out of a mapping) into `matsciml.common.registry`. The "improvement" so to speak would be to also include `arg`/`kwarg` validation, similar to [this](https://github.com/IntelLabs/matsciml/blob/430712f57af820fc918538324cb8c3f2b1947795/matsciml/models/common.py#L210) and I think also in `MACEWrapper`. I think you want to raise an exception if someone passes something that isn't recognized, and this would be a good place to put it (even as a `staticmethod` of `Registry`).

2024-07-01 19:53 UTC, laserkelvin commented on experiments/datasets/data_module_config.py
Do you want to move this things into the main datasets module?

You could repackage these functions as a `from_config` class method, then you don't need to include `__init__.py` in this folder. It _could_ mess up `pip install`s

2024-07-01 19:53 UTC, laserkelvin commented on experiments/README.md
> +The starting point of defining an experiment is the experiment config. This is a yaml file that lays out what model, dataset(s), and task(s) will be used during training. An example config for single
Typo on `single_tasl.yaml`

2024-07-01 19:53 UTC, laserkelvin commented on experiments/datasets/materials_project.yaml
> +  test_split: ./matsciml/datasets/materiasl_project/devset
Is this intentional? I don't think it would point to anything

2024-07-01 19:53 UTC, laserkelvin commented on experiments/task_config/task_config.py
> +task_map = {
Would you like to have it so that each task can have a private variable `__alias__` that we could map to?

e.g.:

```python
class ForceRegressionTask:
    __alias__ = "fr"

    def __init__(self, ...):
```

We could then generate the mapping in `models.base`:

```python
# in models/base.py

alias_map = {}
for key in __all__:
    # not sure if this works, but something to this effect
    alias_map[key] = getattr(__file__, key)
```

Alternatively, we could actually use the registry?

```python
from matsciml.common.registry import registry

# once again in models/base.py
for key in __all__:
    registry.register_model(getattr(__file__, key), key)

# and then use registry in `setup_task`
```

2024-07-11 21:16 UTC, melo-gonzo commented on experiments/README.md
> +The starting point of defining an experiment is the experiment config. This is a yaml file that lays out what model, dataset(s), and task(s) will be used during training. An example config for single
fixed [81b8e06](https://github.com/IntelLabs/matsciml/pull/246/commits/81b8e060ffc66a2ecba6ded9a7c518f7018b1921)

2024-07-11 21:16 UTC, melo-gonzo commented on experiments/datasets/materials_project.yaml
> +  test_split: ./matsciml/datasets/materiasl_project/devset
fixed [2bad280](https://github.com/IntelLabs/matsciml/pull/246/commits/2bad280616fb9f72aa3045662dc502e37367bfa1)

2024-07-11 21:18 UTC, melo-gonzo commented on experiments/task_config/task_config.py
> +task_map = {
I went ahead and purged the 'task_map', and opting to just specify the task class name and using the registry to get out the actual class object. In [this](https://github.com/IntelLabs/matsciml/pull/246/commits/f4364032b4ab8b69b82d40e3ea7ff70ed56ec106) commit

2024-07-11 21:23 UTC, melo-gonzo commented
> bb140fb

I added the class argument verification check in [this](https://github.com/IntelLabs/matsciml/pull/246/commits/bb140fbc92f06a2526da62fdf8ba270ad0ce7e8f) commit. I'm not sure it makes sense to refactor the object creation function `instantiate_arg_dict` and the argument checker `verify_class_args` into the `Registry` class, because these functions also are used to spin up lightning classes such as callbacks and loggers, and other random functions that may not be a part of the registered objects, such as matsciml.datasets.utils.element_types`, and lots of the MACE moules.

2024-07-12 15:55 UTC, melo-gonzo commented on experiments/datasets/data_module_config.py
I think I'd prefer to keep this separate from the datasets module since it is also relying on other experiment related utils such as the command line parsing. If there ends up being other use cases where this functionality would be helpful from the dataset module we can do a refactor then.

2024-07-15 21:57 UTC, laserkelvin requested changes

2024-07-15 21:57 UTC, laserkelvin commented on experiments/README.md
> +    "sr","scalar_regression" -> ScalarRegressionTask
So this shortened version won't work anymore, right?

2024-07-15 21:57 UTC, laserkelvin commented on experiments/datasets/__init__.py
> +yaml_dir = yaml_dir = os.path.dirname(os.path.abspath(__file__))
I'll make this optional for you, but just looks cleaner if you use `pathlib` instead:

```python
from pathlib import Path
yaml_dir = Path(__file__)

for filename in yaml_dir.rglob("*.yaml"):
    ...
```

2024-07-15 21:57 UTC, laserkelvin commented on experiments/datasets/tests/test_data_module_creation.py
> +        "s2ef": {"sr": "energy", "fr": ["force"]},
Do the abbreviations still work?

2024-07-15 21:57 UTC, laserkelvin commented on experiments/models/__init__.py
> +yaml_dir = yaml_dir = os.path.dirname(os.path.abspath(__file__))
Same comment as for `datasets`, use `pathlib` instead of `os.path`

2024-07-15 21:57 UTC, laserkelvin commented on experiments/trainer_config/__init__.py
> +yaml_dir = yaml_dir = os.path.dirname(os.path.abspath(__file__))
Same comment for `pathlib`

2024-07-15 21:57 UTC, laserkelvin commented on experiments/training_script.py
> +    parser.add_argument("-o", "--options", action="store_true")
Could you add `help=...` for each of these arguments? I imagine running `python training_script.py --help` would be a common theme

2024-07-15 21:57 UTC, laserkelvin commented on matsciml/models/base.py
> +                sample[src_nodes.to(int)][None, :]
I think you want to do `src_nodes.long()` and `dst_nodes.long()` instead, since it's less ambiguous.

2024-07-15 22:33 UTC, melo-gonzo commented on experiments/README.md
> +    "sr","scalar_regression" -> ScalarRegressionTask
fixed [759a4fc](https://github.com/IntelLabs/matsciml/pull/246/commits/759a4fc94a377e49141fbab531b3fb393d7af02f)

2024-07-15 22:33 UTC, melo-gonzo commented on experiments/datasets/__init__.py
> +yaml_dir = yaml_dir = os.path.dirname(os.path.abspath(__file__))
fixed [759a4fc](https://github.com/IntelLabs/matsciml/pull/246/commits/759a4fc94a377e49141fbab531b3fb393d7af02f)

2024-07-15 22:33 UTC, melo-gonzo commented on experiments/datasets/tests/test_data_module_creation.py
> +        "s2ef": {"sr": "energy", "fr": ["force"]},
fixed [759a4fc](https://github.com/IntelLabs/matsciml/pull/246/commits/759a4fc94a377e49141fbab531b3fb393d7af02f)

2024-07-15 22:33 UTC, melo-gonzo commented on experiments/models/__init__.py
> +yaml_dir = yaml_dir = os.path.dirname(os.path.abspath(__file__))
fixed [759a4fc](https://github.com/IntelLabs/matsciml/pull/246/commits/759a4fc94a377e49141fbab531b3fb393d7af02f)

2024-07-15 22:33 UTC, melo-gonzo commented on experiments/trainer_config/__init__.py
> +yaml_dir = yaml_dir = os.path.dirname(os.path.abspath(__file__))
fixed [759a4fc](https://github.com/IntelLabs/matsciml/pull/246/commits/759a4fc94a377e49141fbab531b3fb393d7af02f)

2024-07-15 22:33 UTC, melo-gonzo commented on experiments/training_script.py
> +    parser.add_argument("-o", "--options", action="store_true")
fixed [35e44e9](https://github.com/IntelLabs/matsciml/pull/246/commits/35e44e9d4cd3b530952009a96c4a25dfba27c97d)

2024-07-15 22:34 UTC, melo-gonzo commented on matsciml/models/base.py
> +                sample[src_nodes.to(int)][None, :]
fixed [8e11437](https://github.com/IntelLabs/matsciml/pull/246/commits/8e1143709dd38cf49b4a275c8685136fe25931eb)

2024-07-15 23:13 UTC, laserkelvin approved these changes
Thanks for making all the changes, LGTM!

2024-07-15 23:13 UTC, merged