Stress Calculation in `ForceRegressionTask`
IntelLabs/matsciml pull request #302
Opened 2024-10-04 22:59 UTC by melo-gonzo

This PR adds the ability to perform stress calculations inside the `ForceRegressionTask`, and is inspired by the implementation here: https://github.com/ACEsuit/mace/blob/main/mace/modules/utils.py. This functionality if usefull in downstream tasks that require this parameter, and will be helpful for future MatSciML tasks such as a `StressRegressionTask` or similar.

2024-10-04 23:31 UTC, laserkelvin commented
I personally prefer `StressfulTask`

2024-10-07 20:08 UTC, laserkelvin requested changes

2024-10-07 20:08 UTC, laserkelvin commented on matsciml/models/base.py
> +                    torch.abs(stress) < 1e10, stress, torch.zeros_like(stress)
What is this hard coded value?

For something like this, I don't actually know if it's actually more performant to just clip values, instead of using `torch.where` where you have to allocate a `zeros_like` tensor.

2024-10-07 20:08 UTC, laserkelvin commented on matsciml/models/base.py
> +    def get_symmetric_displacement(
If you were inspired by another repo for this function (and others), please add a link to them in the function's docstring

2024-10-07 20:08 UTC, laserkelvin commented on pyproject.toml
How come you removed this?

2024-10-07 20:30 UTC, melo-gonzo commented on matsciml/models/base.py
> +    def get_symmetric_displacement(
added [d0be28d](https://github.com/IntelLabs/matsciml/pull/302/commits/d0be28d4874b06a68e917c0bc5a598dc548c82f4)

2024-10-07 20:31 UTC, melo-gonzo commented on pyproject.toml
Not sure how that got purged. Updated [acd5c4a](https://github.com/IntelLabs/matsciml/pull/302/commits/acd5c4a393dca2dc930c7b77f8a0749f96677b71)

2024-10-07 20:32 UTC, melo-gonzo commented on matsciml/models/base.py
> +                    torch.abs(stress) < 1e10, stress, torch.zeros_like(stress)
this is an inspired bit from [here](https://github.com/ACEsuit/mace/blob/118a514efde34d963666118ce45360e94d648ef5/mace/modules/utils.py#L64). im assuming it is helpful in tasks which compute losses from stress. happy to remove the line and reconsider adding it back if/when we do stress related training.

2024-10-07 20:32 UTC, melo-gonzo commented on matsciml/models/base.py
> +            type[nn.Module] | nn.Module | dict[str, nn.Module | type[nn.Module]] | None
This is just formatting

2024-10-07 20:34 UTC, melo-gonzo commented
> For now this is fine, but I have to say that `ForceRegressionTask` is now reaching unmaintainable levels, now that we have both frame averaging and stress/virial logic spread out across `process_embedding` and other functions. We really need to think about reabstracting stuff where it makes sense. Not saying we need to do it for this PR, but sooner rather than later.

I agree, it could use some organizing.

2024-10-10 17:54 UTC, merged