Adding PyG Version of FAENet
IntelLabs/matsciml pull request #66
Opened 2023-11-17 19:55 UTC by melo-gonzo

This PR adds the FAENet architecture, and frame averaging transform, which may be used with other architectures. Additionally, a transform for calculating a material's unit cell from lattice parameters is added, which is needed to generate extra keys to use FAENet. 

Original FAENet implementation: https://github.com/vict0rsch/faenet

2023-11-17 21:24 UTC, laserkelvin commented on matsciml/common/utils.py
What is all this??

2023-11-17 21:25 UTC, laserkelvin commented on matsciml/common/utils.py
Oh, did `black` just run on this file for the first time?

2023-11-17 21:26 UTC, laserkelvin commented on matsciml/datasets/transforms/props.py
> +        abc, angles = lattice_params[:3], lattice_params[3:]
Do you need to convert angles back to degrees for `Lattice`?

2023-11-17 21:28 UTC, melo-gonzo commented on matsciml/common/utils.py
Yeah I think its from black or one of the pre-commit hooks. I just had to update an import here, `from torch_scatter import segment_coo, segment_csr`, and then things got reformatted like crazy. Happy to revert that if you'd like.

2023-11-17 21:28 UTC, laserkelvin commented on matsciml/models/common.py
Did you edit anything in this file that isn't from the hooks?

2023-11-17 21:29 UTC, laserkelvin commented on matsciml/models/pyg/faenet/helper.py
> +def swish(x):
Is this really necessarily LOL

2023-11-17 21:29 UTC, laserkelvin commented on matsciml/models/pyg/faenet/helper.py
> +    pos,
I'll help with this, but just wanted to leave a TODO to add type annotations (even though there are comments)

2023-11-17 21:31 UTC, laserkelvin commented on matsciml/common/utils.py
I think we're through the looking glass: since you knew exactly what you've done I'd say we keep it. The pain is just separating actual code changes from the pre-commit stuff, so in the future I think we should run the hooks on every file in one big PR but until then I run the pre-commit hooks to check for issues but I don't add the style changes to the commit if they're not relevant.

2023-11-17 21:33 UTC, melo-gonzo commented on matsciml/models/common.py
I did actually, but I'm realizing now that my change is unnecessary - I will revert this file back to original.

2023-11-17 21:37 UTC, melo-gonzo commented on matsciml/models/pyg/faenet/helper.py
> +def swish(x):
No comment here other than I just copied this part in from [original implementation ].(https://github.com/vict0rsch/faenet/blob/1f725cfabb0ef47a44662eac7bc39325249226b2/faenet/utils.py#L12)

2023-11-17 21:41 UTC, laserkelvin commented on matsciml/models/pyg/faenet/helper.py
> +def swish(x):
I don't think it's used anywhere, can we delete it?

2023-11-28 00:10 UTC, melo-gonzo commented on matsciml/models/pyg/faenet/helper.py
> +def swish(x):
[It is used](https://github.com/melo-gonzo/matsciml/blob/3a0852afdd76c34f72113751a55b17a4a25a9729/matsciml/models/pyg/faenet/faenet.py#L149), i guess people usually want to use "swish" for "silu" becasue it sounds cooler? Not sure, i think we should just leave it in for now.

2023-11-28 00:17 UTC, melo-gonzo commented on matsciml/datasets/transforms/props.py
> +        abc, angles = lattice_params[:3], lattice_params[3:]
Good catch, fixed this. Assumes those lattice params angles are in radians though. Not sure if that is true for all datasets.

2023-11-28 01:08 UTC, laserkelvin commented on matsciml/models/pyg/faenet/helper.py
> +def swish(x):
Not a hill I'll die on (and you don't have to do it) but IMO if this is the kind of configuration we want to use, then we should set it up via the `registry`

2023-11-29 20:36 UTC, melo-gonzo commented on matsciml/models/pyg/faenet/helper.py
> +def swish(x):
Purged out the swish ✅

2023-11-29 21:05 UTC, laserkelvin requested changes

2023-11-29 21:05 UTC, laserkelvin commented on matsciml/models/pyg/faenet/faenet.py
> +class FAENet(AbstractPyGModel):
Can you add this to the model registry?

```python
from matsciml.common.registry import registry
...

@registry.register_model("FAENet")
class FAENet(AbstractPyGModel):
    ...
```

2023-11-29 21:05 UTC, laserkelvin commented on matsciml/models/pyg/faenet/faenet.py
> +        if frame_averaging and frame_averaging != "DA":
Because of L391, it will never be "DA" right?

2023-11-29 21:05 UTC, laserkelvin commented on matsciml/models/pyg/faenet/faenet.py
> +                embeddings = self.first_forward(deepcopy(batch))
I left this in, but do we actually need to do a `deepcopy`? Somewhat inefficient

2023-11-29 22:03 UTC, melo-gonzo commented on matsciml/common/utils.py
i believe i added in this import: `from torch_scatter import segment_coo, segment_csr`. other than that it was from pre-commit.

2023-11-29 22:16 UTC, melo-gonzo commented on matsciml/models/pyg/faenet/faenet.py
> +        if frame_averaging and frame_averaging != "DA":
it can be DA if that is what the transform uses. originally i hard coded that variable for simplicity. just changed up the model init args to take `frame_averaging` as an argument to make it consistent.

2023-11-29 22:23 UTC, melo-gonzo commented on matsciml/models/pyg/faenet/faenet.py
> +                embeddings = self.first_forward(deepcopy(batch))
deepcopy doesn't seem to do anything useful anymore.. i removed it.

2023-12-01 17:53 UTC, laserkelvin approved these changes
LGTM, please merge when you're ready!

2023-12-01 17:55 UTC, merged