Adding MACE model and equivariant output block
IntelLabs/matsciml pull request #72
Opened 2023-11-28 06:12 UTC by Vaibhav525

🚀 Feature request
To add MACE pyg model and an equivariant output block. 
Request attributes
      - Would this be a refactor of existing code? - Yes 
      - Does this proposal require new package dependencies? - Yes e3nn
      - Would this change break backwards compatibility? -No
      - Does this proposal include a new model? -Yes , MACE
      - Does this proposal include a new dataset? -No
      - Does this proposal include a new task/workflow? Yes, equivariant output block

2024-01-04 17:57 UTC, laserkelvin commented on matsciml/models/common.py
> +        # if self.residual:
You shouldn't need to comment this block out: you can just pass `residual=False` as an output block kwarg to skip this step.

2024-01-05 20:19 UTC, laserkelvin commented on matsciml/models/common.py
> +        # if self.residual:
Reverted in 0ea49f

2024-01-08 15:59 UTC, laserkelvin commented on matsciml/models/pyg/mace/tools/train.py
Will need to review if this module is actually required since we have our own training pipeline

2024-01-08 22:23 UTC, laserkelvin commented on matsciml/models/pyg/mace/modules/models.py
> +from matsciml.models.pyg.mace.data import AtomicData , get_neighborhood
I'm not seeing `models.pyg.mace.data` as a module being committed, can you please double check the source for these functions?

2024-01-09 15:38 UTC, Vaibhav525 commented on matsciml/models/pyg/mace/modules/models.py
> +from matsciml.models.pyg.mace.data import AtomicData , get_neighborhood
Fixed it now, 'data' was present in .gitignore. I have removed it now.

2024-01-22 16:17 UTC, Vaibhav525 commented
@laserkelvin  Kindly review the code for mace training for energy and forces. A notebook for the same is available at https://github.com/Vaibhav525/matsciml/blob/main/MACE_EF.ipynb and a script is added at https://github.com/Vaibhav525/matsciml/blob/main/matsciml/models/pyg/mace/Train_script.py

2024-01-22 21:53 UTC, laserkelvin requested changes
Summarizing my review:

1. Please include attributions to original code bases including license information if you did not write the original file. This can just be a comment block at the top of the file saying that the original implementation comes from the MACE team, licensed under MIT license,.
2. There's a lot of code committed in this PR, and to me there are likely a lot of functions that are not being accessed. We can merge for now, but likely needs a fair bit of work to refactor and clean later down the line.
3. In the future, please make sure you adhere to [`CONTRIBUTING.md`](./CONTRIBUTING.md) for code style and linting.

2024-01-22 21:53 UTC, laserkelvin commented on matsciml/models/pyg/mace/tools/__init__.py
If this file is from the original implementation, please add attribution at the top of the file

2024-01-22 21:53 UTC, laserkelvin commented on matsciml/models/pyg/mace/tools/scatter.py
Can you confirm this is not needed anymore, because of the header message?

If it's needed still, please add attribution to the top of this file.

2024-01-22 21:53 UTC, laserkelvin commented on test_notebook copy.ipynb
What is the difference between this and the other test notebook?

If you think this notebook will be helpful to others, please format it appropriately by adding comments, etc. and moving it into `examples/model_demos/mace`. If you *don't* intend for this to be read by other people, please remove it.

2024-01-22 21:53 UTC, laserkelvin commented on test_notebook.ipynb
Please see my other notebook comment.

2024-01-22 21:53 UTC, laserkelvin commented on MACE_EF.ipynb
If you intend for this to be used by others, please move it to `examples/model_demos/mace`

2024-01-22 21:53 UTC, laserkelvin commented on datasets_test.ipynb
From the name of this notebook, it doesn't sound like it's useful for other people, so please remove it.

If you think it contains good spot checks, please add a unit test suite instead.

2024-01-23 13:47 UTC, Vaibhav525 commented on .gitignore
Done, added `data`  back.

2024-01-23 14:05 UTC, Vaibhav525 commented on datasets_test.ipynb
Removed.

2024-01-23 14:13 UTC, Vaibhav525 commented on matsciml/models/base.py
> +            modules[key] = OutputHead(**self.output_kwargs).to(self.device)
It breaks the `matsciml/models/tests/test_multi_task.py`. I have reverted the change, as the class is 'Scalar' Regression fixing output dimension to 1 makes sense.

2024-01-23 14:18 UTC, Vaibhav525 commented on matsciml/models/base.py
> +class MaceEnergyForceTask(BaseTaskModule):
I agree we can merge the functionalities of the two classes in future.

2024-01-23 14:19 UTC, Vaibhav525 commented on matsciml/models/base.py
> +    def on_train_batch_start(self, batch: Any, batch_idx: int) -> Optional[int]:
I had added torch.enable_grad() , not sure why it is not highlighting the change.

2024-01-23 14:20 UTC, Vaibhav525 commented on matsciml/models/base.py
> +    def test_step(
I had added torch.enable_grad() , not sure why it is not highlighting the change.

2024-01-23 14:23 UTC, Vaibhav525 commented on matsciml/models/base.py
> +    def validation_step(
This is taken from `ScalarRegressionTask` Class, and has some modification with respect to parent class `BaseTaskModule`

2024-01-23 14:24 UTC, Vaibhav525 commented on matsciml/models/base.py
> +    def process_embedding(self, embeddings: Embeddings) -> Dict[str, torch.Tensor]:
Yes, i only added functions that has some changes.

2024-01-23 14:24 UTC, Vaibhav525 commented on matsciml/models/base.py
> +            if self.loss_coeff==None:
Apologies for it. I will keep that in mind for future.

2024-01-23 14:48 UTC, Vaibhav525 commented on matsciml/models/common.py
> +        output = data
Changed to return data directly

2024-01-23 14:49 UTC, Vaibhav525 commented on matsciml/models/common.py
> +    def input_dim(self) -> int:
Any dimension works for this layer. I have set it to -1 now. Let me know if there's a better way to do this.

2024-01-23 14:50 UTC, Vaibhav525 commented on matsciml/models/pyg/mace/Train_script.py
Moved.

2024-01-23 15:08 UTC, Vaibhav525 commented on matsciml/models/pyg/mace/tools/scatter.py
It can be replaced by `torch.scatter_reduce`  but that is currently in beta version of torch. Let's keep it for now. I have added the attributions.

2024-01-23 15:09 UTC, Vaibhav525 commented on pl-configs/models/mace.yml
Removed.

2024-01-23 15:10 UTC, Vaibhav525 commented on test_notebook copy.ipynb
Removed

2024-01-23 15:10 UTC, Vaibhav525 commented on test_notebook.ipynb
Removed

2024-01-23 15:19 UTC, Vaibhav525 reviewed
I have addressed most of the raised comments. Kindly review.

2024-01-23 16:04 UTC, laserkelvin approved these changes
At a high level things look like they're at a merge-able state to me. I think it would be good if @melo-gonzo does a quick review as well, in which case @smiret-intel will be able to merge.

2024-01-23 19:00 UTC, melo-gonzo commented on examples/model_demos/mace/MACE_EF_Train.py
> +import pytest
Can you clean up the unused imports here? Example scripts are good ways to showcase minimum requirements to get models training.

2024-01-23 19:00 UTC, melo-gonzo commented on examples/model_demos/mace/MACE_EF_Train.py
> +    trainer.fit(task, datamodule=dm)
Add `fast_dev_run=10` here to limit the example to run only a few batches to show functionality.

2024-01-23 19:00 UTC, melo-gonzo commented on matsciml/models/base.py
> +            output = reduce(output, "b ... d -> b d", reduction="mean")
A reduction strategy can be set in the task config and is accessed by `self.embedding_reduction_type`, defaults to 'mean'.

2024-01-23 19:04 UTC, melo-gonzo approved these changes
I left a few comments, mostly things that can be cleaned up. I would suggest we keep refining the implementation and additions over time to remove unnecessary added code, ensure consistent styling and formatting, and ensure efficient use of the existing matsciml api and tools which exist in the repo already.

2024-01-24 00:42 UTC, merged